export const vehiclesSeed = [
  {
    name: 'Mini Cooper',
    year: 2021,
    bodywork: 'Hatch compacto',
    engine: 'Motor 1.8',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Ford Ká',
    year: 2017,
    bodywork: 'Hatch médio',
    engine: 'Motor 1.0',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Duster',
    year: 2020,
    bodywork: 'SUV compacto',
    engine: 'Motor 1.6',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Jeep Compass',
    year: 2021,
    bodywork: 'SUV médio',
    engine: 'Motor 1.8',
    seats: 7,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Toro',
    year: 2016,
    bodywork: 'Picape média',
    engine: 'Motor 1.6',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'T-Cross',
    year: 2020,
    bodywork: 'Crossover',
    engine: 'Motor 1.6',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Strada',
    year: 2016,
    bodywork: 'Picape leve',
    engine: 'Motor 1.4',
    seats: 2,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Saveiro',
    year: 2018,
    bodywork: 'Picape leve-média',
    engine: 'Motor 1.6',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Versa',
    year: 2019,
    bodywork: 'Sedan médio',
    engine: 'Motor 1.4',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Jetta',
    year: 2021,
    bodywork: 'Sedan grande',
    engine: 'Motor 2.0',
    seats: 5,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Doblô',
    year: 2018,
    bodywork: 'Minivan',
    engine: 'Motor 1.8',
    seats: 7,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Fiorino',
    year: 2017,
    bodywork: 'Utilitário leve',
    engine: 'Motor 1.6',
    seats: 2,
    active: true,
    inactiveReason: null,
  },
  {
    name: 'Partner',
    year: 2016,
    bodywork: 'Utilitário',
    engine: 'Motor 1.6',
    seats: 2,
    active: true,
    inactiveReason: null,
  },
];
